# -*- coding: utf-8 -*-
"""Second Zuber Ahmad - Future First Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oC_pvoJZGhf7ijXzCaH9Jd9o_eni9PNV
"""

# Commented out IPython magic to ensure Python compatibility.
# Import necessary modules
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline
import plotly.graph_objects as go
from datetime import datetime
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/My Drive/Colab Notebooks/Almax/Fture first/German 10 YR Bund Futures Historical Data.csv')

# Make a list of columns
col = df.columns.tolist()

col = list(col[:1]) + list(col[2:5]) + list(col[1:2]) + list(col[5:7])      # shifting columns as required
df = df[col]          #Reordered the dataframe

# Renaming Price column to Close
df = df.rename(columns={'Price': 'Close'})

from datetime import datetime

fig = go.Figure(data=[go.Candlestick(x=df['Date'],
                open=df['Open'],
                high=df['High'],
                low=df['Low'],
                close=df['Close'])])

fig.update_layout(
    autosize=False,
    width=1800,
    height=800,)
fig.update_layout(
    title='The Great Recession',
    yaxis_title='Stock',
    )

fig.show()

"""https://ahmad-zuber.github.io/Frontend.github.io/

https://github.com/Ahmad-Zuber/futurefirstassignment.github.io
"""